---
global:
  pattern: opea-chatqna-on-amd
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  amd_llm:
    namespace: amd-llm
    build_envs: []
    runtime_envs: []
  buildEnabled: false

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true

